from config import Config

QM_SUPPLIER = 'QM'
PPO_SUPPLIER = 'PPO'

QM3_2_DATASET = 'QM3.2'
QM3_4_DATASET = 'QM3.4'
PPD1_1_DATASET = 'PPD1.1'
PPD1_3_DATASET = 'PPD1.3'

PACK_CODE_TO_SFTP_DIRECTORY = {
    'P_IC_ICL1': Config.SFTP_PPO_DIRECTORY,
    'P_IC_ICL2B': Config.SFTP_PPO_DIRECTORY,
    'P_IC_ICL4': Config.SFTP_PPO_DIRECTORY,
    'P_IC_H1': Config.SFTP_QM_DIRECTORY,
    'P_IC_H2': Config.SFTP_QM_DIRECTORY,
    'P_IC_H4': Config.SFTP_QM_DIRECTORY,
    'P_OR_H1': Config.SFTP_QM_DIRECTORY,
    'P_OR_H2': Config.SFTP_QM_DIRECTORY,
    'P_OR_H2W': Config.SFTP_QM_DIRECTORY,
    'P_OR_H4': Config.SFTP_QM_DIRECTORY,
    "P_LP_HL1": Config.SFTP_PPO_DIRECTORY,
    "P_LP_HL2": Config.SFTP_PPO_DIRECTORY,
    "P_LP_HL2W": Config.SFTP_PPO_DIRECTORY,
    "P_LP_HL4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBARA1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBBEN1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBCAN1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBCAN4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBFRE1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBGUJ1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBGUR1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBIRI4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBITA1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBKUR1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBLIT1": Config.SFTP_PPO_DIRECTORY,
    "T_PB_TBLIT4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBMAN1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBMAN4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBPOL1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBPOL4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBPOR1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBRUS1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBSOM1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBSPA1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBTUR1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBULS4": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBVIE1": Config.SFTP_PPO_DIRECTORY,
    "P_TB_TBYSH1": Config.SFTP_PPO_DIRECTORY,
}

PACK_CODE_TO_DATASET = {
    'P_IC_ICL1': PPD1_1_DATASET,
    'P_IC_ICL2B': PPD1_1_DATASET,
    'P_IC_ICL4': PPD1_1_DATASET,
    'P_IC_H1': QM3_2_DATASET,
    'P_IC_H2': QM3_2_DATASET,
    'P_IC_H4': QM3_2_DATASET,
    'P_OR_H1': QM3_4_DATASET,
    'P_OR_H2': QM3_4_DATASET,
    'P_OR_H2W': QM3_4_DATASET,
    'P_OR_H4': QM3_4_DATASET,
    "P_LP_HL1": PPD1_3_DATASET,
    "P_LP_HL2": PPD1_3_DATASET,
    "P_LP_HL2W": PPD1_3_DATASET,
    "P_LP_HL4": PPD1_3_DATASET,
    "P_TB_TBARA1": PPD1_3_DATASET,
    "P_TB_TBBEN1": PPD1_3_DATASET,
    "P_TB_TBCAN1": PPD1_3_DATASET,
    "P_TB_TBCAN4": PPD1_3_DATASET,
    "P_TB_TBFRE1": PPD1_3_DATASET,
    "P_TB_TBGUJ1": PPD1_3_DATASET,
    "P_TB_TBGUR1": PPD1_3_DATASET,
    "P_TB_TBIRI4": PPD1_3_DATASET,
    "P_TB_TBITA1": PPD1_3_DATASET,
    "P_TB_TBKUR1": PPD1_3_DATASET,
    "P_TB_TBLIT1": PPD1_3_DATASET,
    "T_PB_TBLIT4": PPD1_3_DATASET,
    "P_TB_TBMAN1": PPD1_3_DATASET,
    "P_TB_TBMAN4": PPD1_3_DATASET,
    "P_TB_TBPOL1": PPD1_3_DATASET,
    "P_TB_TBPOL4": PPD1_3_DATASET,
    "P_TB_TBPOR1": PPD1_3_DATASET,
    "P_TB_TBRUS1": PPD1_3_DATASET,
    "P_TB_TBSOM1": PPD1_3_DATASET,
    "P_TB_TBSPA1": PPD1_3_DATASET,
    "P_TB_TBTUR1": PPD1_3_DATASET,
    "P_TB_TBULS4": PPD1_3_DATASET,
    "P_TB_TBVIE1": PPD1_3_DATASET,
    "P_TB_TBYSH1": PPD1_3_DATASET,
}

PACK_CODE_TO_DESCRIPTION = {
    'P_IC_ICL1': 'Initial contact letter households - England',
    'P_IC_ICL2B': 'Initial contact letter households - Wales',
    'P_IC_ICL4': 'Initial contact letter households - Northern Ireland',
    'P_IC_H1': 'Initial contact questionnaire households - England',
    'P_IC_H2': 'Initial contact questionnaire households - Wales',
    'P_IC_H4': 'Initial contact questionnaire households - Northern Ireland',
    'P_OR_H1': 'Household Questionnaire for England',
    'P_OR_H2': 'Household Questionnaire for Wales (English)',
    'P_OR_H2W': 'Household Questionnaire for Wales (Welsh)',
    'P_OR_H4': 'Household Questionnaire for Northern Ireland (English)',
    "P_LP_HL1": 'Household Questionnaire Large Print pack for England',
    "P_LP_HL2": 'Household Questionnaire Large Print pack for Wales (English)',
    "P_LP_HL2W": 'Household Questionnaire Large Print pack for Wales (Welsh)',
    "P_LP_HL4": 'Household Questionnaire Large Print pack for Northern Ireland',
    "P_TB_TBARA1": 'Translation Booklet for England & Wales - Arabic',
    "P_TB_TBBEN1": 'Translation Booklet for England & Wales - Bengali',
    "P_TB_TBCAN1": 'Translation Booklet for England & Wales - Cantonese',
    "P_TB_TBCAN4": 'Translation Booklet for Northern Ireland - Cantonese',
    "P_TB_TBFRE1": 'Translation Booklet for England & Wales - French',
    "P_TB_TBGUJ1": 'Translation Booklet for England & Wales - Gujarati',
    "P_TB_TBGUR1": 'Translation Booklet for England & Wales - Panjabi – Gurmukhi',
    "P_TB_TBIRI4": 'Translation Booklet for Northern Ireland - Irish',
    "P_TB_TBITA1": 'Translation Booklet for England & Wales - Italian',
    "P_TB_TBKUR1": 'Translation Booklet for England & Wales - Kurdish',
    "P_TB_TBLIT1": 'Translation Booklet for England & Wales - Lithuanian',
    "T_PB_TBLIT4": 'Translation Booklet for Northern Ireland - Lithuanian',
    "P_TB_TBMAN1": 'Translation Booklet for England & Wales - Mandarin Chinese',
    "P_TB_TBMAN4": 'Translation Booklet for Northern Ireland - Mandarin',
    "P_TB_TBPOL1": 'Translation Booklet for England & Wales - Polish',
    "P_TB_TBPOL4": 'Translation Booklet for Northern Ireland - Polish',
    "P_TB_TBPOR1": 'Translation Booklet for England & Wales - Portuguese',
    "P_TB_TBRUS1": 'Translation Booklet for England & Wales - Russian',
    "P_TB_TBSOM1": 'Translation Booklet for England & Wales - Somali',
    "P_TB_TBSPA1": 'Translation Booklet for England & Wales - Spanish',
    "P_TB_TBTUR1": 'Translation Booklet for England & Wales - Turkish',
    "P_TB_TBULS4": 'Translation Booklet for Northern Ireland - Ulster-Scots',
    "P_TB_TBURD1": 'Translation Booklet for England & Wales - Urdu',
    "P_TB_TBVIE1": 'Translation Booklet for England & Wales - Vietnamese',
    "P_TB_TBYSH1": 'Translation Booklet for England & Wales - Yiddish',
}
