import os


class Config(object):

    SECURITY_USER_NAME = os.getenv('SECURITY_USER_NAME', 'admin')
    SECURITY_USER_PASSWORD = os.getenv('SECURITY_USER_PASSWORD', 'secret')
    BASIC_AUTH = (SECURITY_USER_NAME, SECURITY_USER_PASSWORD)

    PROTOCOL = os.getenv('PROTOCOL', 'http')

    ACTION_SERVICE_HOST = os.getenv('ACTION_SERVICE_HOST', 'actionsvc')
    ACTION_SERVICE_PORT = os.getenv('ACTION_SERVICE_PORT', 80)
    ACTION_SERVICE = f'{PROTOCOL}://{ACTION_SERVICE_HOST}:{ACTION_SERVICE_PORT}'

    SURVEY_SERVICE_HOST = os.getenv('SURVEY_SERVICE_HOST', 'surveysvc')
    SURVEY_SERVICE_PORT = os.getenv('SURVEY_SERVICE_PORT', 80)
    SURVEY_SERVICE = f'{PROTOCOL}://{SURVEY_SERVICE_HOST}:{SURVEY_SERVICE_PORT}'

    COLLECTION_EXERCISE_HOST = os.getenv('COLLECTION_EXERCISE_HOST', 'collectionexercisesvc')
    COLLECTION_EXERCISE_PORT = os.getenv('COLLECTION_EXERCISE_PORT', 80)
    COLLECTION_EXERCISE = f'{PROTOCOL}://{COLLECTION_EXERCISE_HOST}:{COLLECTION_EXERCISE_PORT}'
